"""create users table

Revision ID: 99b69737c38e
Revises: d0d87d86a391
Create Date: 2025-03-22 22:02:35.311854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99b69737c38e"
down_revision: Union[str, None] = "d0d87d86a391"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tripmate;")
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "email_confirmed",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tripmate",
    )
    op.create_index(
        op.f("ix_tripmate_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="tripmate",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tripmate_users_email"), table_name="users", schema="tripmate"
    )
    op.drop_table("users", schema="tripmate")
    # ### end Alembic commands ###
