"""add map_url field for city and country

Revision ID: f5a5e4f9b64d
Revises: 9a94e3b010a3
Create Date: 2025-04-08 10:31:13.270954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a5e4f9b64d'
down_revision: Union[str, None] = '9a94e3b010a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('map_url', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('map_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'map_url')
    op.drop_column('cities', 'map_url')
    # ### end Alembic commands ###
